version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

  playwright-tests:
    build: .
    container_name: playwright-tests
    restart: unless-stopped
    volumes:
      - ./screenshots:/app/screenshots
      - ./playwright-report:/app/playwright-report
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - NODE_ENV=production
    networks:
      - jenkins-network
    depends_on:
      - jenkins

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - jenkins-network
    depends_on:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge 